apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
data:
  master.cnf: |
    [client]
    default-character-set=utf8
    # Master
    [mysqld]
    character-set-server=utf8
    log-bin=master-bin
    skip-name-resolve
  slave.cnf: |
    [client]
    default-character-set=utf8
    # Slave
    [mysqld]
    character-set-server=utf8
    super-read-only
    skip-name-resolve
    log-bin=slave-bin
    replicate-ignore-db=mysql
