apiVersion: v1
kind: Pod
metadata:
  name: test-configfile-po
spec:
  containers:
    - name: config-test
      image: alpine
      command: ["/bin/sh", "-c", "sleep 3600"]
      imagePullPolicy: IfNotPresent
      env:
      - name: JAVA_VM_OPTS
        valueFrom:
          configMapKeyRef:
            name: test-env-config # configMap 的名字
            key: JAVA_OPTS_TEST # 表示从 name 的 ConfigMap 中获取名字为 key 的 value，将其赋值给本地环境变量 JAVA_VM_OPTS
      - name: APP
        valueFrom:
          configMapKeyRef:
            name: test-env-config
            key: APP_NAME
      volumeMounts: # 加载数据卷
      - name: db-config # 表示加载 volumes 属性中哪个数据卷
        mountPath: "/usr/local/mysql/conf" # 想要将数据卷中的文件加载到哪个目录下
        readOnly: true # 是否只读
  volumes: # 数据卷挂载 configmap、secret
    - name: db-config # 数据卷的名字，随意设置
      configMap: # 数据卷类型为 CofngiMap
        name: test-dir-config # configMap 的名字，必须跟想要加载的 configmap 相同
        items: # 对 configmap 中的 key 进行映射，如果不指定，默认会讲 configmap 中所有 key 全部转换为一个个同名的文件
        - key: "db.properties" # configMap 中的 key
          path: "db.properties" # 将该 key 的值转换为文件
  restartPolicy: Never
