---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongodb
  labels:
    app: mongodb
spec:
  type: NodePort
  ports:
  - name: mongo
    port: 27017
    nodePort: 30017
    protocol: TCP
  selector:
    app: mongodb
---
apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: mongodb
  namespace: mongodb
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:2.2.7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
          name: web # 该端口配置的名字
  volumeClaimTemplates:
  - metadata:
      name: mongodb
      namespace: mongodb
    spec:
      storageClassName: managed-nfs-storage
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 1Gi
